version: 2

jobs:
  build:
    working_directory: ~/work-in-timezone
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - restore_cache:
          key: yarndeps-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Installing javascript dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarndeps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Linting the source code
          command: yarn lint
      - run:
          name: Typechecking the source code
          command: yarn typecheck

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
